import type {
  Provider,
  AgentProfile,
  Destination,
  SavingsStats,
  LeaderboardEntry,
  MarketTicker,
  IntelligenceConnector,
  KnowledgeGraphNode,
  TeamAgent,
  CalendarSuggestion,
  VehicleOption,
  DriverProfile,
  ContinuousOptEvent,
  CommunityIntel,
} from "./types";

// Accra city center — matches user timezone Africa/Accra
export const CITY_CENTER = { lat: 5.6037, lng: -0.187 };

export const PROVIDERS: Provider[] = [
  {
    id: "uber",
    name: "Uber",
    category: "ride-hail",
    color: "#1a1a1a",
    emoji: "U",
    baseFare: 6,
    perKm: 1.9,
    perMin: 0.35,
    rating: 4.7,
    reliability: 0.92,
    features: ["electric", "luggage"],
  },
  {
    id: "bolt",
    name: "Bolt",
    category: "ride-hail",
    color: "#2bc553",
    emoji: "B",
    baseFare: 5,
    perKm: 1.7,
    perMin: 0.3,
    rating: 4.6,
    reliability: 0.88,
    features: ["luggage"],
  },
  {
    id: "yango",
    name: "Yango",
    category: "ride-hail",
    color: "#ff4d4d",
    emoji: "Y",
    baseFare: 4.5,
    perKm: 1.6,
    perMin: 0.28,
    rating: 4.5,
    reliability: 0.85,
    features: [],
  },
  {
    id: "indrive",
    name: "inDrive",
    category: "ride-hail",
    color: "#c1f11d",
    emoji: "i",
    baseFare: 4,
    perKm: 1.5,
    perMin: 0.25,
    rating: 4.4,
    reliability: 0.8,
    features: [],
  },
  {
    id: "taxi",
    name: "City Taxi",
    category: "taxi",
    color: "#f5a623",
    emoji: "T",
    baseFare: 5.5,
    perKm: 1.8,
    perMin: 0.3,
    rating: 4.3,
    reliability: 0.78,
    features: ["luggage", "pet-friendly"],
  },
  {
    id: "moto",
    name: "Okada Moto",
    category: "moto",
    color: "#ff6b35",
    emoji: "M",
    baseFare: 2,
    perKm: 0.8,
    perMin: 0.1,
    rating: 4.2,
    reliability: 0.9,
    features: ["fast"],
  },
  {
    id: "shuttle",
    name: "Shared Shuttle",
    category: "shuttle",
    color: "#7b61ff",
    emoji: "S",
    baseFare: 1.5,
    perKm: 0.5,
    perMin: 0.08,
    rating: 4.1,
    reliability: 0.82,
    features: ["shared", "electric"],
  },
  {
    id: "luxury",
    name: "Oryx Black",
    category: "luxury",
    color: "#d4af37",
    emoji: "★",
    baseFare: 12,
    perKm: 3.2,
    perMin: 0.5,
    rating: 4.9,
    reliability: 0.95,
    features: ["luxury", "electric", "luggage", "child-seat"],
  },
];

export const AGENTS: AgentProfile[] = [
  {
    id: "balanced",
    name: "Balanced",
    tagline: "Smart savings, reasonable wait",
    description:
      "Negotiates a fair price without long detours. Books when savings clear 18%.",
    maxWait: 6,
    walkTolerance: 150,
    negotiateIntensity: 0.5,
    icon: "Scale",
    color: "#72b1a6",
  },
  {
    id: "aggressive-saver",
    name: "Aggressive Saver",
    tagline: "Waits, negotiates hard",
    description:
      "Hunts the lowest fare. Will wait up to 9 minutes and counter every bid.",
    maxWait: 9,
    walkTolerance: 250,
    negotiateIntensity: 0.78,
    icon: "Crosshair",
    color: "#f5a623",
  },
  {
    id: "maximum-saver",
    name: "Maximum Saver",
    tagline: "Walks farther, allows transfers",
    description:
      "Multi-hop master. Combines walk + shuttle + ride to crush the price floor.",
    maxWait: 14,
    walkTolerance: 500,
    negotiateIntensity: 0.92,
    icon: "PiggyBank",
    color: "#4ade80",
  },
  {
    id: "rush",
    name: "Rush Mode",
    tagline: "No bargaining, fastest pickup",
    description: "Skip the auction. Locks the nearest vehicle the instant you tap.",
    maxWait: 0,
    walkTolerance: 80,
    negotiateIntensity: 0.1,
    icon: "Zap",
    color: "#ef4444",
  },
  {
    id: "luxury",
    name: "Luxury Agent",
    tagline: "Only premium rides",
    description: "Filters to Oryx Black and top-rated executive fleets only.",
    maxWait: 4,
    walkTolerance: 100,
    negotiateIntensity: 0.3,
    icon: "Crown",
    color: "#d4af37",
  },
  {
    id: "business",
    name: "Business Agent",
    tagline: "Company policy compliant",
    description: "Enforces corporate fare caps and preferred providers automatically.",
    maxWait: 5,
    walkTolerance: 120,
    negotiateIntensity: 0.45,
    icon: "Briefcase",
    color: "#a78bfa",
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: "airport",
    name: "Kotoka Int'l Airport",
    address: "Airport Rd, Accra",
    lat: 5.6051,
    lng: -0.1668,
    category: "suggested",
    emoji: "✈️",
  },
  {
    id: "mall",
    name: "Accra Mall",
    address: "Spintex Rd, Accra",
    lat: 5.6262,
    lng: -0.1769,
    category: "suggested",
    emoji: "🛍️",
  },
  {
    id: "labadi",
    name: "Labadi Beach Hotel",
    address: "Labadi Rd, Accra",
    lat: 5.5731,
    lng: -0.1824,
    category: "saved",
    emoji: "🏖️",
  },
  {
    id: "osu",
    name: "Osu Night Market",
    address: "Oxford St, Osu, Accra",
    lat: 5.5597,
    lng: -0.1757,
    category: "recent",
    emoji: "🍜",
  },
  {
    id: "circle",
    name: "Kwame Nkrumah Circle",
    address: "Ring Road Central, Accra",
    lat: 5.5731,
    lng: -0.2053,
    category: "recent",
    emoji: "🔄",
  },
  {
    id: "stadium",
    name: "Accra Sports Stadium",
    address: "Ring Rd E, Accra",
    lat: 5.5753,
    lng: -0.1967,
    category: "event",
    emoji: "🏟️",
  },
  {
    id: "university",
    name: "University of Ghana",
    address: "Legon, Accra",
    lat: 5.6522,
    lng: -0.1862,
    category: "saved",
    emoji: "🎓",
  },
  {
    id: "office",
    name: "The Octagon",
    address: "Independence Ave, Accra",
    lat: 5.5636,
    lng: -0.2026,
    category: "saved",
    emoji: "🏢",
  },
];

export const SAVINGS_STATS: SavingsStats = {
  totalSaved: 618,
  ytdSaved: 412,
  ridesCount: 87,
  co2Saved: 34.6,
  hoursSaved: 11.4,
  streak: 6,
  belowAvgPct: 78,
  rank: 142,
  neighborhoodRank: 3,
};

export const LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, name: "Kwame A.", avatar: "KA", saved: 2841, rides: 312, streak: 47, change: 0 },
  { rank: 2, name: "Ama O.", avatar: "AO", saved: 2614, rides: 288, streak: 33, change: 1 },
  { rank: 3, name: "Yusuf I.", avatar: "YI", saved: 2403, rides: 271, streak: 41, change: -1 },
  { rank: 4, name: "Esi B.", avatar: "EB", saved: 2105, rides: 245, streak: 22, change: 2 },
  { rank: 5, name: "Daniel M.", avatar: "DM", saved: 1988, rides: 233, streak: 19, change: 0 },
  { rank: 6, name: "Fatima A.", avatar: "FA", saved: 1876, rides: 221, streak: 28, change: 3 },
  { rank: 7, name: "Kojo P.", avatar: "KP", saved: 1742, rides: 209, streak: 15, change: -2 },
  { rank: 8, name: "Akosua T.", avatar: "AT", saved: 1620, rides: 198, streak: 11, change: 1 },
];

export const MARKET_TICKERS: MarketTicker[] = [
  { id: "1", text: "Labadi → Airport auction cleared at $11.40", type: "auction" },
  { id: "2", text: "Osu pool matched · 4 riders · $6.20 each", type: "pool" },
  { id: "3", text: "Surge clearing on Spintex in 7 min · −34%", type: "alert" },
  { id: "4", text: "Ama saved $4.10 on her last ride", type: "saving" },
  { id: "5", text: "Stadium demand pooling: 120 riders batching", type: "pool" },
  { id: "6", text: "3 new independent drivers joined East Legon", type: "saving" },
  { id: "7", text: "Rain expected 18:40 · book in 12 min to save 31%", type: "alert" },
  { id: "8", text: "Oryx+ subscribers averaging 23% below city median", type: "saving" },
];

export const DRIVER_NAMES = [
  "Kofi Mensah",
  "Yaw Boateng",
  "Ibrahim Suleiman",
  "Grace Adjei",
  "Samuel Owusu",
  "Amina Hassan",
  "Michael Tetteh",
  "Rashid Mohammed",
  "Comfort Asante",
  "Emmanuel Quaye",
  "Aisha Bello",
  "Daniel Adjei",
];

export const VEHICLES = [
  "Toyota Corolla",
  "Hyundai Elantra",
  "Kia Picanto",
  "Honda Civic",
  "Toyota Vitz",
  "Suzuki Swift",
  "Nissan Almera",
  "Hyundai Accent",
];

// Generate vehicle markers around a center point
export function generateVehicles(
  center: { lat: number; lng: number },
  count = 14
) {
  const vehicles = [];
  for (let i = 0; i < count; i++) {
    const provider = PROVIDERS[Math.floor(Math.random() * 5)];
    const angle = Math.random() * Math.PI * 2;
    const radius = 0.004 + Math.random() * 0.02;
    vehicles.push({
      id: `v-${i}`,
      providerId: provider.id,
      lat: center.lat + Math.sin(angle) * radius,
      lng: center.lng + Math.cos(angle) * radius,
      heading: Math.floor(Math.random() * 360),
      eta: Math.floor(1 + Math.random() * 9),
    });
  }
  return vehicles;
}

// Compute a fare quote for a provider given distance/duration
export function computeFare(
  provider: Provider,
  distanceKm: number,
  durationMin: number,
  surge = 1
) {
  const price =
    (provider.baseFare + provider.perKm * distanceKm + provider.perMin * durationMin) *
    surge;
  return Math.round(price * 100) / 100;
}

// Haversine distance in km
export function haversine(
  a: { lat: number; lng: number },
  b: { lat: number; lng: number }
) {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const lat1 = (a.lat * Math.PI) / 180;
  const lat2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

// ===========================================================================
// AI Mobility Intelligence Network — data
// ===========================================================================

export const CONNECTORS = [
  {
    id: "gmaps",
    name: "Google Maps",
    category: "mapping" as const,
    emoji: "🗺️",
    status: "live" as const,
    signals: ["routing", "live traffic", "incidents", "ETA"],
    latencyMs: 120,
    color: "#4ade80",
  },
  {
    id: "osm",
    name: "OpenStreetMap",
    category: "mapping" as const,
    emoji: "🛣️",
    status: "live" as const,
    signals: ["road network", "closures", "speeds"],
    latencyMs: 90,
    color: "#72b1a6",
  },
  {
    id: "uber",
    name: "Uber API",
    category: "ride-hail" as const,
    emoji: "U",
    status: "live" as const,
    signals: ["pricing", "ETA", "surge", "availability"],
    latencyMs: 340,
    color: "#1a1a1a",
  },
  {
    id: "bolt",
    name: "Bolt API",
    category: "ride-hail" as const,
    emoji: "B",
    status: "live" as const,
    signals: ["pricing", "ETA", "fleet"],
    latencyMs: 280,
    color: "#2bc553",
  },
  {
    id: "yango",
    name: "Yango API",
    category: "ride-hail" as const,
    emoji: "Y",
    status: "syncing" as const,
    signals: ["pricing", "ETA"],
    latencyMs: 410,
    color: "#ff4d4d",
  },
  {
    id: "indrive",
    name: "inDrive",
    category: "ride-hail" as const,
    emoji: "i",
    status: "live" as const,
    signals: ["driver bids", "negotiated fares"],
    latencyMs: 220,
    color: "#c1f11d",
  },
  {
    id: "weather",
    name: "Weather Stream",
    category: "weather" as const,
    emoji: "🌧️",
    status: "live" as const,
    signals: ["rain", "wind", "flood risk", "heat index"],
    latencyMs: 800,
    color: "#22d3ee",
  },
  {
    id: "events",
    name: "Event Feed",
    category: "events" as const,
    emoji: "🎉",
    status: "live" as const,
    signals: ["concerts", "matches", "conferences", "rallies"],
    latencyMs: 1500,
    color: "#f5a623",
  },
  {
    id: "calendar",
    name: "Calendar Sync",
    category: "calendar" as const,
    emoji: "📅",
    status: "connected" as const,
    signals: ["meetings", "recurring trips", "reminders"],
    latencyMs: 60,
    color: "#a78bfa",
  },
  {
    id: "transit",
    name: "Public Transit",
    category: "transit" as const,
    emoji: "🚌",
    status: "live" as const,
    signals: ["bus schedules", "metro", "shuttles", "ferries"],
    latencyMs: 600,
    color: "#fb923c",
  },
  {
    id: "driver-intel",
    name: "Driver Network",
    category: "driver" as const,
    emoji: "🚗",
    status: "live" as const,
    signals: ["hours", "zones", "earnings", "capacity"],
    latencyMs: 180,
    color: "#facc15",
  },
  {
    id: "rider-intel",
    name: "Rider Preferences",
    category: "rider" as const,
    emoji: "🧍",
    status: "connected" as const,
    signals: ["walking tolerance", "budget", "history", "favorites"],
    latencyMs: 40,
    color: "#f472b6",
  },
];

export const KNOWLEDGE_GRAPH: KnowledgeGraphNode[] = [
  { id: "riders", label: "Riders", type: "rider", count: 18420, color: "#72b1a6" },
  { id: "drivers", label: "Drivers", type: "driver", count: 3120, color: "#facc15" },
  { id: "vehicles", label: "Vehicles", type: "vehicle", count: 3480, color: "#a78bfa" },
  { id: "roads", label: "Road segments", type: "road", count: 9420, color: "#4ade80" },
  { id: "neighborhoods", label: "Neighborhoods", type: "neighborhood", count: 64, color: "#22d3ee" },
  { id: "events", label: "Live events", type: "event", count: 12, color: "#f5a623" },
  { id: "weather", label: "Weather cells", type: "weather", count: 8, color: "#60a5fa" },
  { id: "prices", label: "Price points", type: "price", count: 28640, color: "#fb7185" },
];

export const TEAM_AGENTS: TeamAgent[] = [
  {
    id: "savings",
    name: "Savings Agent",
    role: "Reduces cost",
    emoji: "💰",
    color: "#4ade80",
    status: "active",
    activity: "Negotiating 3 concurrent auctions · avg −24%",
    metrics: [
      { label: "Negotiated", value: "$184/wk" },
      { label: "Win rate", value: "91%" },
    ],
    contribution: 38,
  },
  {
    id: "pooling",
    name: "Pooling Agent",
    role: "Finds carpools",
    emoji: "🧑‍🤝‍🧑",
    color: "#a78bfa",
    status: "thinking",
    activity: "Scanning 42 nearby riders heading your direction",
    metrics: [
      { label: "Pools formed", value: "18 today" },
      { label: "Avg split", value: "−47%" },
    ],
    contribution: 22,
  },
  {
    id: "calendar",
    name: "Calendar Agent",
    role: "Optimizes timing",
    emoji: "📅",
    color: "#f472b6",
    status: "active",
    activity: "Found 2 schedule shifts saving GH₵41 this week",
    metrics: [
      { label: "Shifts found", value: "6/mo" },
      { label: "Avg save", value: "GH₵23" },
    ],
    contribution: 14,
  },
  {
    id: "safety",
    name: "Safety Agent",
    role: "Guards wellbeing",
    emoji: "🛡️",
    color: "#60a5fa",
    status: "idle",
    activity: "Monitoring route conditions · all clear",
    metrics: [
      { label: "Risk score", value: "Low" },
      { label: "Routes vetted", value: "312" },
    ],
    contribution: 6,
  },
  {
    id: "time",
    name: "Time Agent",
    role: "Optimizes arrival",
    emoji: "⏱️",
    color: "#22d3ee",
    status: "active",
    activity: "Re-routing around Spintex congestion · −6 min",
    metrics: [
      { label: "Time saved", value: "11.4h" },
      { label: "Re-routes", value: "4 today" },
    ],
    contribution: 10,
  },
  {
    id: "market",
    name: "Market Agent",
    role: "Watches every marketplace",
    emoji: "📊",
    color: "#f5a623",
    status: "active",
    activity: "Surge clearing on 3 corridors in <10 min",
    metrics: [
      { label: "Anomalies", value: "2 found" },
      { label: "Promos", value: "5 active" },
    ],
    contribution: 8,
  },
  {
    id: "learning",
    name: "Learning Agent",
    role: "Improves the team",
    emoji: "🧠",
    color: "#fb7185",
    status: "thinking",
    activity: "Training on 2,840 trips · model v312 live",
    metrics: [
      { label: "Accuracy", value: "94.2%" },
      { label: "Model", value: "v312" },
    ],
    contribution: 2,
  },
];

export const CALENDAR_SUGGESTIONS: CalendarSuggestion[] = [
  {
    id: "c1",
    event: "Team standup",
    originalTime: "3:00 PM",
    suggestedTime: "4:00 PM",
    originalCost: 52,
    suggestedCost: 29,
    saving: 23,
    reason: "Surge clears after 3:45 PM. Off-peak window opens.",
    confidence: 88,
  },
  {
    id: "c2",
    event: "Dentist · Osu",
    originalTime: "5:30 PM",
    suggestedTime: "5:10 PM",
    originalCost: 38,
    suggestedCost: 20,
    saving: 18,
    reason: "Leave 20 min earlier to avoid rush-hour surge.",
    confidence: 76,
  },
  {
    id: "c3",
    event: "Airport pickup",
    originalTime: "Tomorrow 8:00 AM",
    suggestedTime: "Tomorrow 7:40 AM",
    originalCost: 74,
    suggestedCost: 58,
    saving: 16,
    reason: "Pre-book 2 days ahead — drivers fill schedules cheaper.",
    confidence: 92,
  },
];

export const VEHICLE_OPTIONS: VehicleOption[] = [
  {
    id: "moto",
    name: "Motorcycle",
    emoji: "🏍️",
    capacity: 1,
    basePrice: 3,
    bestFor: "Beat traffic, solo",
    eta: 2,
    available: 48,
    co2: "low",
  },
  {
    id: "scooter",
    name: "E-Scooter",
    emoji: "🛴",
    capacity: 1,
    basePrice: 2,
    bestFor: "Last-mile, short hops",
    eta: 3,
    available: 22,
    co2: "low",
  },
  {
    id: "tuktuk",
    name: "Tuk-tuk",
    emoji: "🛺",
    capacity: 3,
    basePrice: 4,
    bestFor: "Short urban trips",
    eta: 4,
    available: 15,
    co2: "low",
  },
  {
    id: "sedan",
    name: "Sedan",
    emoji: "🚗",
    capacity: 4,
    basePrice: 8,
    bestFor: "Everyday comfort",
    eta: 3,
    available: 124,
    co2: "medium",
    recommended: true,
  },
  {
    id: "suv",
    name: "SUV",
    emoji: "🚙",
    capacity: 6,
    basePrice: 14,
    bestFor: "Groups, luggage",
    eta: 5,
    available: 38,
    co2: "high",
  },
  {
    id: "van",
    name: "Van",
    emoji: "🚐",
    capacity: 8,
    basePrice: 18,
    bestFor: "Family, team travel",
    eta: 6,
    available: 12,
    co2: "high",
  },
  {
    id: "minibus",
    name: "Minibus",
    emoji: "🚌",
    capacity: 15,
    basePrice: 3,
    bestFor: "Shared shuttle",
    eta: 8,
    available: 6,
    co2: "low",
  },
  {
    id: "ev",
    name: "Electric",
    emoji: "⚡",
    capacity: 4,
    basePrice: 9,
    bestFor: "Zero-emission rides",
    eta: 4,
    available: 28,
    co2: "low",
  },
  {
    id: "av",
    name: "Autonomous",
    emoji: "🤖",
    capacity: 4,
    basePrice: 7,
    bestFor: "Future fleets",
    eta: 9,
    available: 3,
    co2: "low",
  },
];

export const DRIVER_PROFILES: DriverProfile[] = [
  {
    id: "d1",
    name: "Kofi Mensah",
    avatar: "KM",
    vehicle: "Toyota Corolla",
    vehicleType: "sedan",
    rating: 4.9,
    reputation: 96,
    earningsGoal: { weekly: 1800, progress: 78 },
    efficiency: 41,
    savingsGenerated: 1240,
    pooledTrips: 64,
    punctuality: 98,
    champion: true,
    zone: "East Legon",
  },
  {
    id: "d2",
    name: "Grace Adjei",
    avatar: "GA",
    vehicle: "Hyundai Kona EV",
    vehicleType: "ev",
    rating: 4.9,
    reputation: 94,
    earningsGoal: { weekly: 1600, progress: 82 },
    efficiency: 52,
    savingsGenerated: 980,
    pooledTrips: 71,
    punctuality: 96,
    champion: true,
    zone: "Osu",
  },
  {
    id: "d3",
    name: "Ibrahim Suleiman",
    avatar: "IS",
    vehicle: "Yamaha Moto",
    vehicleType: "moto",
    rating: 4.7,
    reputation: 88,
    earningsGoal: { weekly: 900, progress: 64 },
    efficiency: 68,
    savingsGenerated: 610,
    pooledTrips: 0,
    punctuality: 92,
    zone: "Spintex",
  },
  {
    id: "d4",
    name: "Ama Boateng",
    avatar: "AB",
    vehicle: "Toyota HiAce",
    vehicleType: "van",
    rating: 4.8,
    reputation: 91,
    earningsGoal: { weekly: 2200, progress: 71 },
    efficiency: 38,
    savingsGenerated: 1530,
    pooledTrips: 142,
    punctuality: 94,
    zone: "Airport",
  },
];

export const CONTINUOUS_OPT_EVENTS: ContinuousOptEvent[] = [
  {
    id: "o1",
    phase: "before",
    time: "−2:14",
    title: "AI scanned 1,284 providers",
    detail: "Filtered to 8 candidates · ranked by price + ETA + safety",
    type: "scan",
  },
  {
    id: "o2",
    phase: "before",
    time: "−0:08",
    title: "Reverse auction cleared",
    detail: "Won at $11.40 — 41% below baseline",
    saving: 7.6,
    type: "switch",
  },
  {
    id: "o3",
    phase: "during",
    time: "now",
    title: "Re-routing around incident",
    detail: "Minor accident on Ring Road · saved 6 min via Labadi",
    saving: 0,
    type: "alert",
  },
  {
    id: "o4",
    phase: "during",
    time: "+1:30",
    title: "Pool merge offered",
    detail: "Ama nearby · merge to cut your fare $6",
    saving: 6,
    type: "switch",
  },
  {
    id: "o5",
    phase: "after",
    time: "+3:00",
    title: "Still watching for cheaper options",
    detail: "Will auto-switch if equivalent ride drops below your fare",
    type: "scan",
  },
  {
    id: "o6",
    phase: "after",
    time: "trip end",
    title: "Learning from this trip",
    detail: "Updates city demand model + driver reliability scores",
    type: "learn",
  },
];

export const COMMUNITY_INTEL: CommunityIntel = {
  tripsAnalyzed: 2840610,
  routesLearned: 18420,
  poolsDiscovered: 9240,
  demandPatterns: 312,
  activeConnectors: 12,
  networkIq: 87,
};
